console.log('typeof "a" is: ', typeof "a");
console.log("typeof 5 is: ",typeof 5);
console.log("typeof true is: ",typeof true);
console.log('typeof undefined is: ' ,typeof undefined);
console.log('typeof null is :' , typeof null);
console.log("typeof [0] is: " ,typeof [0]);
console.log("20% of 100 is" + (20/100)*100);
console.log("2*2 = ", 2*2);
console.log("2 + 2 = " ,2+2);
console.log("2 / 2 = " , 2/2);
console.log('2 - 1 = ', 2-1);
console.log('10 % 3 = ',10 % 3);
console.log(`"5" + 2 = `,'5'+2);
console.log(`"5" - 2 = `,'5'-2);
console.log("!true = " , !true);
console.log("5 === 5 = ", 5 === 5);
console.log("5 !== 5 = ", 5 !== 5);
console.log("true && false = ",true && false);
console.log("true || false = ",true || false);
console.log("!false = ", !false );
const isAdult = age => age > 18 ? true : false;
const isEven = (num) => num % 2 === 0 ?true : false;
const fullName = (fstName, scndName) => `${fstName} ${scndName}`;
const greet = name => ` Hello ${name}`;
const discount = (price,percent) => (percent/100)*price;
console.log(isAdult(32));
console.log(isEven(32));
console.log(fullName('rwakarama','patient'));
console.log(greet('Cherife'));
console.log(discount(1000,20));